/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrunlerRouteImport } from './routes/urunler'
import { Route as SssRouteImport } from './routes/sss'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NasilCalisirRouteImport } from './routes/nasil-calisir'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as KosullarRouteImport } from './routes/kosullar'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as IadeRouteImport } from './routes/iade'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UrunSlugRouteImport } from './routes/urun.$slug'
import { Route as OdemeOrderIdRouteImport } from './routes/odeme.$orderId'
import { Route as BakiyeYukleTopupIdRouteImport } from './routes/bakiye-yukle.$topupId'
import { Route as ApiValidateRouteImport } from './routes/api/validate'
import { Route as ApiRevokeRouteImport } from './routes/api/revoke'
import { Route as ApiActivateRouteImport } from './routes/api/activate'
import { Route as AktivasyonTokenRouteImport } from './routes/aktivasyon.$token'
import { Route as AuthenticatedHesabimRouteImport } from './routes/_authenticated/hesabim'
import { Route as AuthenticatedFavorilerimRouteImport } from './routes/_authenticated/favorilerim'
import { Route as AuthenticatedCuzdanRouteImport } from './routes/_authenticated/cuzdan'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUrunlerRouteImport } from './routes/_authenticated/admin/urunler'
import { Route as AuthenticatedAdminSiparislerRouteImport } from './routes/_authenticated/admin/siparisler'
import { Route as AuthenticatedAdminPromosyonlarRouteImport } from './routes/_authenticated/admin/promosyonlar'
import { Route as AuthenticatedAdminPopulerRouteImport } from './routes/_authenticated/admin/populer'
import { Route as AuthenticatedAdminLisanslarRouteImport } from './routes/_authenticated/admin/lisanslar'
import { Route as AuthenticatedAdminKuponlarRouteImport } from './routes/_authenticated/admin/kuponlar'
import { Route as AuthenticatedAdminKullanicilarRouteImport } from './routes/_authenticated/admin/kullanicilar'
import { Route as AuthenticatedAdminKeylerRouteImport } from './routes/_authenticated/admin/keyler'
import { Route as AuthenticatedAdminKampanyalarRouteImport } from './routes/_authenticated/admin/kampanyalar'
import { Route as AuthenticatedAdminCuzdanRouteImport } from './routes/_authenticated/admin/cuzdan'
import { Route as AuthenticatedAdminAyarlarRouteImport } from './routes/_authenticated/admin/ayarlar'
import { Route as ApiPublicHooksCampaignTickRouteImport } from './routes/api/public/hooks/campaign-tick'

const UrunlerRoute = UrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => rootRouteImport,
} as any)
const SssRoute = SssRouteImport.update({
  id: '/sss',
  path: '/sss',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NasilCalisirRoute = NasilCalisirRouteImport.update({
  id: '/nasil-calisir',
  path: '/nasil-calisir',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const KosullarRoute = KosullarRouteImport.update({
  id: '/kosullar',
  path: '/kosullar',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const IadeRoute = IadeRouteImport.update({
  id: '/iade',
  path: '/iade',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunSlugRoute = UrunSlugRouteImport.update({
  id: '/urun/$slug',
  path: '/urun/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeOrderIdRoute = OdemeOrderIdRouteImport.update({
  id: '/odeme/$orderId',
  path: '/odeme/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const BakiyeYukleTopupIdRoute = BakiyeYukleTopupIdRouteImport.update({
  id: '/bakiye-yukle/$topupId',
  path: '/bakiye-yukle/$topupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValidateRoute = ApiValidateRouteImport.update({
  id: '/api/validate',
  path: '/api/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevokeRoute = ApiRevokeRouteImport.update({
  id: '/api/revoke',
  path: '/api/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivateRoute = ApiActivateRouteImport.update({
  id: '/api/activate',
  path: '/api/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivasyonTokenRoute = AktivasyonTokenRouteImport.update({
  id: '/aktivasyon/$token',
  path: '/aktivasyon/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHesabimRoute = AuthenticatedHesabimRouteImport.update({
  id: '/hesabim',
  path: '/hesabim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavorilerimRoute =
  AuthenticatedFavorilerimRouteImport.update({
    id: '/favorilerim',
    path: '/favorilerim',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCuzdanRoute = AuthenticatedCuzdanRouteImport.update({
  id: '/cuzdan',
  path: '/cuzdan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUrunlerRoute =
  AuthenticatedAdminUrunlerRouteImport.update({
    id: '/urunler',
    path: '/urunler',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSiparislerRoute =
  AuthenticatedAdminSiparislerRouteImport.update({
    id: '/siparisler',
    path: '/siparisler',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPromosyonlarRoute =
  AuthenticatedAdminPromosyonlarRouteImport.update({
    id: '/promosyonlar',
    path: '/promosyonlar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPopulerRoute =
  AuthenticatedAdminPopulerRouteImport.update({
    id: '/populer',
    path: '/populer',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLisanslarRoute =
  AuthenticatedAdminLisanslarRouteImport.update({
    id: '/lisanslar',
    path: '/lisanslar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKuponlarRoute =
  AuthenticatedAdminKuponlarRouteImport.update({
    id: '/kuponlar',
    path: '/kuponlar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKullanicilarRoute =
  AuthenticatedAdminKullanicilarRouteImport.update({
    id: '/kullanicilar',
    path: '/kullanicilar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKeylerRoute =
  AuthenticatedAdminKeylerRouteImport.update({
    id: '/keyler',
    path: '/keyler',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKampanyalarRoute =
  AuthenticatedAdminKampanyalarRouteImport.update({
    id: '/kampanyalar',
    path: '/kampanyalar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCuzdanRoute =
  AuthenticatedAdminCuzdanRouteImport.update({
    id: '/cuzdan',
    path: '/cuzdan',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAyarlarRoute =
  AuthenticatedAdminAyarlarRouteImport.update({
    id: '/ayarlar',
    path: '/ayarlar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicHooksCampaignTickRoute =
  ApiPublicHooksCampaignTickRouteImport.update({
    id: '/api/public/hooks/campaign-tick',
    path: '/api/public/hooks/campaign-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gizlilik': typeof GizlilikRoute
  '/iade': typeof IadeRoute
  '/iletisim': typeof IletisimRoute
  '/kosullar': typeof KosullarRoute
  '/kvkk': typeof KvkkRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
  '/urunler': typeof UrunlerRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/cuzdan': typeof AuthenticatedCuzdanRoute
  '/favorilerim': typeof AuthenticatedFavorilerimRoute
  '/hesabim': typeof AuthenticatedHesabimRoute
  '/aktivasyon/$token': typeof AktivasyonTokenRoute
  '/api/activate': typeof ApiActivateRoute
  '/api/revoke': typeof ApiRevokeRoute
  '/api/validate': typeof ApiValidateRoute
  '/bakiye-yukle/$topupId': typeof BakiyeYukleTopupIdRoute
  '/odeme/$orderId': typeof OdemeOrderIdRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/admin/ayarlar': typeof AuthenticatedAdminAyarlarRoute
  '/admin/cuzdan': typeof AuthenticatedAdminCuzdanRoute
  '/admin/kampanyalar': typeof AuthenticatedAdminKampanyalarRoute
  '/admin/keyler': typeof AuthenticatedAdminKeylerRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/kuponlar': typeof AuthenticatedAdminKuponlarRoute
  '/admin/lisanslar': typeof AuthenticatedAdminLisanslarRoute
  '/admin/populer': typeof AuthenticatedAdminPopulerRoute
  '/admin/promosyonlar': typeof AuthenticatedAdminPromosyonlarRoute
  '/admin/siparisler': typeof AuthenticatedAdminSiparislerRoute
  '/admin/urunler': typeof AuthenticatedAdminUrunlerRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/campaign-tick': typeof ApiPublicHooksCampaignTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gizlilik': typeof GizlilikRoute
  '/iade': typeof IadeRoute
  '/iletisim': typeof IletisimRoute
  '/kosullar': typeof KosullarRoute
  '/kvkk': typeof KvkkRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
  '/urunler': typeof UrunlerRoute
  '/cuzdan': typeof AuthenticatedCuzdanRoute
  '/favorilerim': typeof AuthenticatedFavorilerimRoute
  '/hesabim': typeof AuthenticatedHesabimRoute
  '/aktivasyon/$token': typeof AktivasyonTokenRoute
  '/api/activate': typeof ApiActivateRoute
  '/api/revoke': typeof ApiRevokeRoute
  '/api/validate': typeof ApiValidateRoute
  '/bakiye-yukle/$topupId': typeof BakiyeYukleTopupIdRoute
  '/odeme/$orderId': typeof OdemeOrderIdRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/admin/ayarlar': typeof AuthenticatedAdminAyarlarRoute
  '/admin/cuzdan': typeof AuthenticatedAdminCuzdanRoute
  '/admin/kampanyalar': typeof AuthenticatedAdminKampanyalarRoute
  '/admin/keyler': typeof AuthenticatedAdminKeylerRoute
  '/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/admin/kuponlar': typeof AuthenticatedAdminKuponlarRoute
  '/admin/lisanslar': typeof AuthenticatedAdminLisanslarRoute
  '/admin/populer': typeof AuthenticatedAdminPopulerRoute
  '/admin/promosyonlar': typeof AuthenticatedAdminPromosyonlarRoute
  '/admin/siparisler': typeof AuthenticatedAdminSiparislerRoute
  '/admin/urunler': typeof AuthenticatedAdminUrunlerRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/campaign-tick': typeof ApiPublicHooksCampaignTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/gizlilik': typeof GizlilikRoute
  '/iade': typeof IadeRoute
  '/iletisim': typeof IletisimRoute
  '/kosullar': typeof KosullarRoute
  '/kvkk': typeof KvkkRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sss': typeof SssRoute
  '/urunler': typeof UrunlerRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/cuzdan': typeof AuthenticatedCuzdanRoute
  '/_authenticated/favorilerim': typeof AuthenticatedFavorilerimRoute
  '/_authenticated/hesabim': typeof AuthenticatedHesabimRoute
  '/aktivasyon/$token': typeof AktivasyonTokenRoute
  '/api/activate': typeof ApiActivateRoute
  '/api/revoke': typeof ApiRevokeRoute
  '/api/validate': typeof ApiValidateRoute
  '/bakiye-yukle/$topupId': typeof BakiyeYukleTopupIdRoute
  '/odeme/$orderId': typeof OdemeOrderIdRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/_authenticated/admin/ayarlar': typeof AuthenticatedAdminAyarlarRoute
  '/_authenticated/admin/cuzdan': typeof AuthenticatedAdminCuzdanRoute
  '/_authenticated/admin/kampanyalar': typeof AuthenticatedAdminKampanyalarRoute
  '/_authenticated/admin/keyler': typeof AuthenticatedAdminKeylerRoute
  '/_authenticated/admin/kullanicilar': typeof AuthenticatedAdminKullanicilarRoute
  '/_authenticated/admin/kuponlar': typeof AuthenticatedAdminKuponlarRoute
  '/_authenticated/admin/lisanslar': typeof AuthenticatedAdminLisanslarRoute
  '/_authenticated/admin/populer': typeof AuthenticatedAdminPopulerRoute
  '/_authenticated/admin/promosyonlar': typeof AuthenticatedAdminPromosyonlarRoute
  '/_authenticated/admin/siparisler': typeof AuthenticatedAdminSiparislerRoute
  '/_authenticated/admin/urunler': typeof AuthenticatedAdminUrunlerRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/campaign-tick': typeof ApiPublicHooksCampaignTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gizlilik'
    | '/iade'
    | '/iletisim'
    | '/kosullar'
    | '/kvkk'
    | '/nasil-calisir'
    | '/sitemap.xml'
    | '/sss'
    | '/urunler'
    | '/admin'
    | '/cuzdan'
    | '/favorilerim'
    | '/hesabim'
    | '/aktivasyon/$token'
    | '/api/activate'
    | '/api/revoke'
    | '/api/validate'
    | '/bakiye-yukle/$topupId'
    | '/odeme/$orderId'
    | '/urun/$slug'
    | '/admin/ayarlar'
    | '/admin/cuzdan'
    | '/admin/kampanyalar'
    | '/admin/keyler'
    | '/admin/kullanicilar'
    | '/admin/kuponlar'
    | '/admin/lisanslar'
    | '/admin/populer'
    | '/admin/promosyonlar'
    | '/admin/siparisler'
    | '/admin/urunler'
    | '/admin/'
    | '/api/public/hooks/campaign-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gizlilik'
    | '/iade'
    | '/iletisim'
    | '/kosullar'
    | '/kvkk'
    | '/nasil-calisir'
    | '/sitemap.xml'
    | '/sss'
    | '/urunler'
    | '/cuzdan'
    | '/favorilerim'
    | '/hesabim'
    | '/aktivasyon/$token'
    | '/api/activate'
    | '/api/revoke'
    | '/api/validate'
    | '/bakiye-yukle/$topupId'
    | '/odeme/$orderId'
    | '/urun/$slug'
    | '/admin/ayarlar'
    | '/admin/cuzdan'
    | '/admin/kampanyalar'
    | '/admin/keyler'
    | '/admin/kullanicilar'
    | '/admin/kuponlar'
    | '/admin/lisanslar'
    | '/admin/populer'
    | '/admin/promosyonlar'
    | '/admin/siparisler'
    | '/admin/urunler'
    | '/admin'
    | '/api/public/hooks/campaign-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/gizlilik'
    | '/iade'
    | '/iletisim'
    | '/kosullar'
    | '/kvkk'
    | '/nasil-calisir'
    | '/sitemap.xml'
    | '/sss'
    | '/urunler'
    | '/_authenticated/admin'
    | '/_authenticated/cuzdan'
    | '/_authenticated/favorilerim'
    | '/_authenticated/hesabim'
    | '/aktivasyon/$token'
    | '/api/activate'
    | '/api/revoke'
    | '/api/validate'
    | '/bakiye-yukle/$topupId'
    | '/odeme/$orderId'
    | '/urun/$slug'
    | '/_authenticated/admin/ayarlar'
    | '/_authenticated/admin/cuzdan'
    | '/_authenticated/admin/kampanyalar'
    | '/_authenticated/admin/keyler'
    | '/_authenticated/admin/kullanicilar'
    | '/_authenticated/admin/kuponlar'
    | '/_authenticated/admin/lisanslar'
    | '/_authenticated/admin/populer'
    | '/_authenticated/admin/promosyonlar'
    | '/_authenticated/admin/siparisler'
    | '/_authenticated/admin/urunler'
    | '/_authenticated/admin/'
    | '/api/public/hooks/campaign-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GizlilikRoute: typeof GizlilikRoute
  IadeRoute: typeof IadeRoute
  IletisimRoute: typeof IletisimRoute
  KosullarRoute: typeof KosullarRoute
  KvkkRoute: typeof KvkkRoute
  NasilCalisirRoute: typeof NasilCalisirRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SssRoute: typeof SssRoute
  UrunlerRoute: typeof UrunlerRoute
  AktivasyonTokenRoute: typeof AktivasyonTokenRoute
  ApiActivateRoute: typeof ApiActivateRoute
  ApiRevokeRoute: typeof ApiRevokeRoute
  ApiValidateRoute: typeof ApiValidateRoute
  BakiyeYukleTopupIdRoute: typeof BakiyeYukleTopupIdRoute
  OdemeOrderIdRoute: typeof OdemeOrderIdRoute
  UrunSlugRoute: typeof UrunSlugRoute
  ApiPublicHooksCampaignTickRoute: typeof ApiPublicHooksCampaignTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urunler': {
      id: '/urunler'
      path: '/urunler'
      fullPath: '/urunler'
      preLoaderRoute: typeof UrunlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sss': {
      id: '/sss'
      path: '/sss'
      fullPath: '/sss'
      preLoaderRoute: typeof SssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasil-calisir': {
      id: '/nasil-calisir'
      path: '/nasil-calisir'
      fullPath: '/nasil-calisir'
      preLoaderRoute: typeof NasilCalisirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosullar': {
      id: '/kosullar'
      path: '/kosullar'
      fullPath: '/kosullar'
      preLoaderRoute: typeof KosullarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iade': {
      id: '/iade'
      path: '/iade'
      fullPath: '/iade'
      preLoaderRoute: typeof IadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urun/$slug': {
      id: '/urun/$slug'
      path: '/urun/$slug'
      fullPath: '/urun/$slug'
      preLoaderRoute: typeof UrunSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme/$orderId': {
      id: '/odeme/$orderId'
      path: '/odeme/$orderId'
      fullPath: '/odeme/$orderId'
      preLoaderRoute: typeof OdemeOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakiye-yukle/$topupId': {
      id: '/bakiye-yukle/$topupId'
      path: '/bakiye-yukle/$topupId'
      fullPath: '/bakiye-yukle/$topupId'
      preLoaderRoute: typeof BakiyeYukleTopupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/validate': {
      id: '/api/validate'
      path: '/api/validate'
      fullPath: '/api/validate'
      preLoaderRoute: typeof ApiValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revoke': {
      id: '/api/revoke'
      path: '/api/revoke'
      fullPath: '/api/revoke'
      preLoaderRoute: typeof ApiRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activate': {
      id: '/api/activate'
      path: '/api/activate'
      fullPath: '/api/activate'
      preLoaderRoute: typeof ApiActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivasyon/$token': {
      id: '/aktivasyon/$token'
      path: '/aktivasyon/$token'
      fullPath: '/aktivasyon/$token'
      preLoaderRoute: typeof AktivasyonTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hesabim': {
      id: '/_authenticated/hesabim'
      path: '/hesabim'
      fullPath: '/hesabim'
      preLoaderRoute: typeof AuthenticatedHesabimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorilerim': {
      id: '/_authenticated/favorilerim'
      path: '/favorilerim'
      fullPath: '/favorilerim'
      preLoaderRoute: typeof AuthenticatedFavorilerimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuzdan': {
      id: '/_authenticated/cuzdan'
      path: '/cuzdan'
      fullPath: '/cuzdan'
      preLoaderRoute: typeof AuthenticatedCuzdanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/urunler': {
      id: '/_authenticated/admin/urunler'
      path: '/urunler'
      fullPath: '/admin/urunler'
      preLoaderRoute: typeof AuthenticatedAdminUrunlerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/siparisler': {
      id: '/_authenticated/admin/siparisler'
      path: '/siparisler'
      fullPath: '/admin/siparisler'
      preLoaderRoute: typeof AuthenticatedAdminSiparislerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/promosyonlar': {
      id: '/_authenticated/admin/promosyonlar'
      path: '/promosyonlar'
      fullPath: '/admin/promosyonlar'
      preLoaderRoute: typeof AuthenticatedAdminPromosyonlarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/populer': {
      id: '/_authenticated/admin/populer'
      path: '/populer'
      fullPath: '/admin/populer'
      preLoaderRoute: typeof AuthenticatedAdminPopulerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lisanslar': {
      id: '/_authenticated/admin/lisanslar'
      path: '/lisanslar'
      fullPath: '/admin/lisanslar'
      preLoaderRoute: typeof AuthenticatedAdminLisanslarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kuponlar': {
      id: '/_authenticated/admin/kuponlar'
      path: '/kuponlar'
      fullPath: '/admin/kuponlar'
      preLoaderRoute: typeof AuthenticatedAdminKuponlarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kullanicilar': {
      id: '/_authenticated/admin/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/admin/kullanicilar'
      preLoaderRoute: typeof AuthenticatedAdminKullanicilarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/keyler': {
      id: '/_authenticated/admin/keyler'
      path: '/keyler'
      fullPath: '/admin/keyler'
      preLoaderRoute: typeof AuthenticatedAdminKeylerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kampanyalar': {
      id: '/_authenticated/admin/kampanyalar'
      path: '/kampanyalar'
      fullPath: '/admin/kampanyalar'
      preLoaderRoute: typeof AuthenticatedAdminKampanyalarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cuzdan': {
      id: '/_authenticated/admin/cuzdan'
      path: '/cuzdan'
      fullPath: '/admin/cuzdan'
      preLoaderRoute: typeof AuthenticatedAdminCuzdanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ayarlar': {
      id: '/_authenticated/admin/ayarlar'
      path: '/ayarlar'
      fullPath: '/admin/ayarlar'
      preLoaderRoute: typeof AuthenticatedAdminAyarlarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/hooks/campaign-tick': {
      id: '/api/public/hooks/campaign-tick'
      path: '/api/public/hooks/campaign-tick'
      fullPath: '/api/public/hooks/campaign-tick'
      preLoaderRoute: typeof ApiPublicHooksCampaignTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAyarlarRoute: typeof AuthenticatedAdminAyarlarRoute
  AuthenticatedAdminCuzdanRoute: typeof AuthenticatedAdminCuzdanRoute
  AuthenticatedAdminKampanyalarRoute: typeof AuthenticatedAdminKampanyalarRoute
  AuthenticatedAdminKeylerRoute: typeof AuthenticatedAdminKeylerRoute
  AuthenticatedAdminKullanicilarRoute: typeof AuthenticatedAdminKullanicilarRoute
  AuthenticatedAdminKuponlarRoute: typeof AuthenticatedAdminKuponlarRoute
  AuthenticatedAdminLisanslarRoute: typeof AuthenticatedAdminLisanslarRoute
  AuthenticatedAdminPopulerRoute: typeof AuthenticatedAdminPopulerRoute
  AuthenticatedAdminPromosyonlarRoute: typeof AuthenticatedAdminPromosyonlarRoute
  AuthenticatedAdminSiparislerRoute: typeof AuthenticatedAdminSiparislerRoute
  AuthenticatedAdminUrunlerRoute: typeof AuthenticatedAdminUrunlerRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAyarlarRoute: AuthenticatedAdminAyarlarRoute,
    AuthenticatedAdminCuzdanRoute: AuthenticatedAdminCuzdanRoute,
    AuthenticatedAdminKampanyalarRoute: AuthenticatedAdminKampanyalarRoute,
    AuthenticatedAdminKeylerRoute: AuthenticatedAdminKeylerRoute,
    AuthenticatedAdminKullanicilarRoute: AuthenticatedAdminKullanicilarRoute,
    AuthenticatedAdminKuponlarRoute: AuthenticatedAdminKuponlarRoute,
    AuthenticatedAdminLisanslarRoute: AuthenticatedAdminLisanslarRoute,
    AuthenticatedAdminPopulerRoute: AuthenticatedAdminPopulerRoute,
    AuthenticatedAdminPromosyonlarRoute: AuthenticatedAdminPromosyonlarRoute,
    AuthenticatedAdminSiparislerRoute: AuthenticatedAdminSiparislerRoute,
    AuthenticatedAdminUrunlerRoute: AuthenticatedAdminUrunlerRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCuzdanRoute: typeof AuthenticatedCuzdanRoute
  AuthenticatedFavorilerimRoute: typeof AuthenticatedFavorilerimRoute
  AuthenticatedHesabimRoute: typeof AuthenticatedHesabimRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCuzdanRoute: AuthenticatedCuzdanRoute,
  AuthenticatedFavorilerimRoute: AuthenticatedFavorilerimRoute,
  AuthenticatedHesabimRoute: AuthenticatedHesabimRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GizlilikRoute: GizlilikRoute,
  IadeRoute: IadeRoute,
  IletisimRoute: IletisimRoute,
  KosullarRoute: KosullarRoute,
  KvkkRoute: KvkkRoute,
  NasilCalisirRoute: NasilCalisirRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SssRoute: SssRoute,
  UrunlerRoute: UrunlerRoute,
  AktivasyonTokenRoute: AktivasyonTokenRoute,
  ApiActivateRoute: ApiActivateRoute,
  ApiRevokeRoute: ApiRevokeRoute,
  ApiValidateRoute: ApiValidateRoute,
  BakiyeYukleTopupIdRoute: BakiyeYukleTopupIdRoute,
  OdemeOrderIdRoute: OdemeOrderIdRoute,
  UrunSlugRoute: UrunSlugRoute,
  ApiPublicHooksCampaignTickRoute: ApiPublicHooksCampaignTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
