/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrunlerRouteImport } from './routes/urunler'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UrunSlugRouteImport } from './routes/urun.$slug'
import { Route as OdemeOrderIdRouteImport } from './routes/odeme.$orderId'

const UrunlerRoute = UrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunSlugRoute = UrunSlugRouteImport.update({
  id: '/urun/$slug',
  path: '/urun/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeOrderIdRoute = OdemeOrderIdRouteImport.update({
  id: '/odeme/$orderId',
  path: '/odeme/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/urunler': typeof UrunlerRoute
  '/odeme/$orderId': typeof OdemeOrderIdRoute
  '/urun/$slug': typeof UrunSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/urunler': typeof UrunlerRoute
  '/odeme/$orderId': typeof OdemeOrderIdRoute
  '/urun/$slug': typeof UrunSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/urunler': typeof UrunlerRoute
  '/odeme/$orderId': typeof OdemeOrderIdRoute
  '/urun/$slug': typeof UrunSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/urunler' | '/odeme/$orderId' | '/urun/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/urunler' | '/odeme/$orderId' | '/urun/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/urunler'
    | '/odeme/$orderId'
    | '/urun/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  UrunlerRoute: typeof UrunlerRoute
  OdemeOrderIdRoute: typeof OdemeOrderIdRoute
  UrunSlugRoute: typeof UrunSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urunler': {
      id: '/urunler'
      path: '/urunler'
      fullPath: '/urunler'
      preLoaderRoute: typeof UrunlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urun/$slug': {
      id: '/urun/$slug'
      path: '/urun/$slug'
      fullPath: '/urun/$slug'
      preLoaderRoute: typeof UrunSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme/$orderId': {
      id: '/odeme/$orderId'
      path: '/odeme/$orderId'
      fullPath: '/odeme/$orderId'
      preLoaderRoute: typeof OdemeOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  UrunlerRoute: UrunlerRoute,
  OdemeOrderIdRoute: OdemeOrderIdRoute,
  UrunSlugRoute: UrunSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
